name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

change-template: "- $TITLE @$AUTHOR ([#$NUMBER](https://github.com/user/repo/pull/$NUMBER))'"
category-template: "### $TITLE"
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: "Breaking Changes"
    labels:
      - "breaking"
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "enhancement"
      - "feature"
  patch:
    labels:
      - "bug"
      - "fix"

exclude-labels:
  - "skip-changelog"
