name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&@' # You can add # and @ to disable mentions, and add ` to disable code blocks.

categories:
  - title: "Breaking Changes 🛠"
    labels:
      - "breaking"
  - title: "New Features 🚀"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "enhancement"
      - "feature"
  patch:
    labels:
      - "bug"
      - "fix"

exclude-labels:
  - "skip-changelog"
