# name: "[AUTOMATE] Update Changelog"
# on:
#   release:
#     types: [released]

# jobs:
#   update:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.release.target_commitish }}
#       - uses: stefanzweifel/changelog-updater-action@v1
#         with:
#           latest-version: ${{ github.event.release.tag_name }}
#           release-notes: ${{ github.event.release.body }}
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           branch: ${{ github.event.release.target_commitish }}
#           commit_message: Update CHANGELOG
#           file_pattern: CHANGELOG.md

name: "[AUTOMATE] Generate changelog"
on:
  release:
    types: [released]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@master
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_MESSAGE: "docs: update CHANGELOG"
          TYPE: "breaking:Breaking Changes,feat:New Features,fix:Bug Fixes,docs:Documentation,refactor:Refactor,ci:CICD"
