name: "[AUTOMATE] Generate changelog"
on:
  release:
    types: [released]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@master
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_MESSAGE: "docs: update CHANGELOG"
          TYPE: ""
