name: "[AUTOMATE] Labling"
on:
  pull_request:
    types: [opened, edited]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"breaking": "breaking", "feat": "enhancement", "fix": "bug"}'
