name: Pull Request
on:
  pull_request:

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"feat": "enhancement", "fix": "bug", "breaking": "breaking"}'
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: enhancement,fix,breaking
          repo_token: ${{ secrets.GITHUB_TOKEN }}
