name: Pull Request

on:
  pull_request:

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: "https://copmany.atlassian.net/browse/OPS-%ticketNumber%"
          ticketPrefix: "OPS-"
          titleRegex: '^OPS-(?<ticketNumber>\d+)'

          bodyRegex: 'OPS-(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(:copmany.atlassian.net)(\/browse)\/(OPS\-)(?<ticketNumber>\d+)'

  check_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: new-feature,breaking-change,bug-fix,docs-update,minor-update,enhancement
          repo_token: ${{ secrets.GITHUB_TOKEN }}
