name: "[AUTOMATE] Labling"
on:
  pull_request:

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          token: ${{ secrets.TOKEN }}
