name: "[AUTOMATE] Release Drafter"
on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          publish: true
          disable-autolabeler: true
