name: "[AUTOMATE] Release Drafter"
on:
  push:
    branches:
      - main
    paths:
      - "**.txt"
      - "modules/**"
      - "terragrunt/**"
      - "!**.md"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          publish: true
